---
- name: Mirror CrowdStrike Container Images to a Private Repository
  hosts: all
  gather_facts: true
  become: false

  module_defaults:
    containers.podman.podman_image:
      auth_file: /tmp/cs-auth.json
    containers.podman.podman_login:
      authfile: /tmp/cs-auth.json

  vars:
    echo_debug: false # Set to true to enable debug output

    crowdstrike_cloud_endpoint: US-2 # default is US-1

    # crowdstrike_customer_id: 1234567890

    remote_registry_endpoint: jfrog.kemo.labs
    remote_registry_image_path: cs-mirror/falcon-sensor
    remote_registry_username: robot-mirror
    remote_registry_password: Passw0rd123!

  tasks:
    - name: Authenticate to the Crowdstrike API and get an Image Registry Token
      ansible.builtin.include_role:
        name: crowdstrike_reg_auth

    - name: Mirror the CrowdStrike Container Images to a Private Repository
      ansible.builtin.include_role:
        name: crowdstrike_mirror_images

    - name: Clean up auth file
      ansible.builtin.file:
        path: /tmp/cs-auth.json
        state: absent
