---

- name: Check if the remote image exists
  ansible.builtin.command: |
    skopeo inspect docker://{{ remote_registry_endpoint }}/{{ remote_registry_image_path }}:{{ image_item }} \
      --authfile /tmp/cs-auth.json
  register: remote_image_exists
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Copy image between registries - {{ image_item }}
  when: remote_image_exists is failed
  ansible.builtin.command: |
    skopeo copy docker://{{ crowdstrike_image_base }}:{{ image_item }} \
      docker://{{ remote_registry_endpoint }}/{{ remote_registry_image_path }}:{{ image_item }} \
      --authfile /tmp/cs-auth.json
  changed_when: true
